package com.smms.backend.config;

import com.smms.backend.model.Product;
import com.smms.backend.repository.ProductRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;

@Component
public class ProductDataLoader implements CommandLineRunner {

    @Autowired
    private ProductRepository productRepository;

    @Override
    public void run(String... args) throws Exception {
        long count = productRepository.findByUserIsNullAndIsDefaultTrue().size();
        if (count < 210) {
            System.out.println("Default products count (" + count + ") is less than expected (210). Re-seeding...");
            // Clear existing system-wide default products (where user is null)
            List<Product> existingDefaults = productRepository.findByUserIsNullAndIsDefaultTrue();
            if (!existingDefaults.isEmpty()) {
                productRepository.deleteAll(existingDefaults);
            }
            seedDefaultProducts();
        }
    }

    private void seedDefaultProducts() {
        List<Product> defaultProducts = Arrays.asList(
                // --- STAPLES & GRAINS (D001 - D030) ---
                new Product(null, "Aashirvaad Atta 5kg", "D001", "Grains", "Atta", 260.0, 245.0, 50, "0%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Fortune Mustard Oil 1L", "D002", "Oils", "Mustard Oil", 150.0, 142.0, 50, "5%",
                        "Default Supplier", LocalDate.now().plusMonths(6), true),
                new Product(null, "Tata Salt 1kg", "D003", "Staples", "Salt", 28.0, 25.0, 100, "0%", "Default Supplier",
                        LocalDate.now().plusYears(2), true),
                new Product(null, "Basmati Rice 5kg", "D009", "Grains", "Rice", 650.0, 599.0, 30, "0%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Sugar 1kg", "D007", "Staples", "Sugar", 48.0, 44.0, 100, "5%", "Default Supplier",
                        LocalDate.now().plusYears(2), true),
                new Product(null, "Moong Dal 1kg", "D008", "Pulses", "Dal", 130.0, 120.0, 50, "0%", "Default Supplier",
                        LocalDate.now().plusYears(1), true),
                new Product(null, "Toor Dal 1kg", "D011", "Pulses", "Dal", 160.0, 145.0, 50, "0%", "Default Supplier",
                        LocalDate.now().plusYears(1), true),
                new Product(null, "Chana Dal 1kg", "D012", "Pulses", "Dal", 90.0, 82.0, 50, "0%", "Default Supplier",
                        LocalDate.now().plusYears(1), true),
                new Product(null, "Urad Dal 1kg", "D013", "Pulses", "Dal", 140.0, 128.0, 50, "0%", "Default Supplier",
                        LocalDate.now().plusYears(1), true),
                new Product(null, "Masoor Dal 1kg", "D014", "Pulses", "Dal", 110.0, 98.0, 50, "0%", "Default Supplier",
                        LocalDate.now().plusYears(1), true),
                new Product(null, "Fortune Sunlite Oil 1L", "D015", "Oils", "Sunflower Oil", 165.0, 155.0, 50, "5%",
                        "Default Supplier", LocalDate.now().plusMonths(6), true),
                new Product(null, "Saffola Gold 1L", "D016", "Oils", "Blended Oil", 195.0, 185.0, 30, "5%",
                        "Default Supplier", LocalDate.now().plusMonths(9), true),
                new Product(null, "Dhara Groundnut Oil 1L", "D017", "Oils", "Groundnut Oil", 210.0, 198.0, 30, "5%",
                        "Default Supplier", LocalDate.now().plusMonths(6), true),
                new Product(null, "Amul Cow Ghee 500ml", "D018", "Dairy", "Ghee", 320.0, 305.0, 25, "12%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Patasala Poha 500g", "D019", "Staples", "Poha", 55.0, 48.0, 50, "0%",
                        "Default Supplier", LocalDate.now().plusMonths(6), true),
                new Product(null, "Fortune Maida 1kg", "D020", "Staples", "Maida", 45.0, 40.0, 50, "0%",
                        "Default Supplier", LocalDate.now().plusMonths(6), true),
                new Product(null, "Fortune Sooji 500g", "D021", "Staples", "Sooji", 35.0, 30.0, 50, "0%",
                        "Default Supplier", LocalDate.now().plusMonths(6), true),
                new Product(null, "Rajma Red 1kg", "D022", "Pulses", "Beans", 180.0, 165.0, 30, "0%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Kabuli Chana 1kg", "D023", "Pulses", "Beans", 150.0, 138.0, 30, "0%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Brown Rice 1kg", "D024", "Grains", "Rice", 120.0, 110.0, 20, "0%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Idli Rice 1kg", "D025", "Grains", "Rice", 60.0, 55.0, 50, "0%", "Default Supplier",
                        LocalDate.now().plusMonths(6), true),

                // --- SPices & CONDIMENTS (D031 - D070) ---
                new Product(null, "Everest Turmeric Powder 100g", "D031", "Spices", "Powder", 35.0, 32.0, 100, "5%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Everest Chilli Powder 100g", "D032", "Spices", "Powder", 45.0, 42.0, 100, "5%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Everest Coriander Powder 100g", "D033", "Spices", "Powder", 32.0, 28.0, 100, "5%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "MDH Garam Masala 100g", "D034", "Spices", "Masala", 85.0, 78.0, 50, "5%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Catch Black Pepper 50g", "D035", "Spices", "Spice", 65.0, 60.0, 50, "5%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Society Tea 250g", "D036", "Beverages", "Tea", 145.0, 135.0, 50, "5%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Wagh Bakri Tea 500g", "D005", "Beverages", "Tea", 310.0, 285.0, 50, "5%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Nescafe Classic 50g", "D037", "Beverages", "Coffee", 165.0, 155.0, 50, "12%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Bru Instant Coffee 50g", "D038", "Beverages", "Coffee", 150.0, 140.0, 50, "12%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Kissan Tomato Ketchup 1kg", "D039", "Condiments", "Sauce", 140.0, 125.0, 30, "12%",
                        "Default Supplier", LocalDate.now().plusMonths(9), true),
                new Product(null, "FunFoods Mayonnaise 250g", "D040", "Condiments", "Sauce", 95.0, 85.0, 30, "12%",
                        "Default Supplier", LocalDate.now().plusMonths(6), true),
                new Product(null, "Smith & Jones Ginger Garlic Paste 200g", "D041", "Spices", "Paste", 50.0, 45.0, 50,
                        "12%", "Default Supplier", LocalDate.now().plusMonths(6), true),
                new Product(null, "Everest Hing 50g", "D042", "Spices", "Spice", 75.0, 70.0, 50, "5%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Catch Jeera Powder 100g", "D043", "Spices", "Powder", 60.0, 55.0, 50, "5%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Everest Pav Bhaji Masala 100g", "D044", "Spices", "Masala", 82.0, 75.0, 50, "5%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "MDH Kitchen King 100g", "D045", "Spices", "Masala", 90.0, 82.0, 50, "5%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Saffola Honey 250g", "D046", "Condiments", "Honey", 115.0, 99.0, 20, "5%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Dabur Chyawanprash 500g", "D047", "Health", "Supplement", 210.0, 195.0, 20, "12%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Horlicks 500g Jar", "D048", "Beverages", "Health Drink", 265.0, 245.0, 25, "18%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Bournvita 500g Refill", "D049", "Beverages", "Health Drink", 240.0, 225.0, 25, "18%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),

                // --- SNACKS & BISCUITS (D071 - D110) ---
                new Product(null, "Maggi Noodles 70g", "D004", "Snacks", "Noodles", 14.0, 12.0, 200, "12%",
                        "Default Supplier", LocalDate.now().plusMonths(9), true),
                new Product(null, "Parle-G 800g", "D006", "Snacks", "Biscuits", 80.0, 75.0, 100, "12%",
                        "Default Supplier", LocalDate.now().plusMonths(6), true),
                new Product(null, "Britannia Good Day Cashew 200g", "D050", "Snacks", "Biscuits", 40.0, 35.0, 100,
                        "12%", "Default Supplier", LocalDate.now().plusMonths(6), true),
                new Product(null, "Britannia Marie Gold 250g", "D051", "Snacks", "Biscuits", 35.0, 30.0, 100, "12%",
                        "Default Supplier", LocalDate.now().plusMonths(6), true),
                new Product(null, "Sunfeast Dark Fantasy 100g", "D052", "Snacks", "Biscuits", 50.0, 45.0, 50, "18%",
                        "Default Supplier", LocalDate.now().plusMonths(6), true),
                new Product(null, "Parle Hide & Seek 120g", "D053", "Snacks", "Biscuits", 30.0, 28.0, 100, "12%",
                        "Default Supplier", LocalDate.now().plusMonths(6), true),
                new Product(null, "Lay's Magic Masala 50g", "D054", "Snacks", "Chips", 20.0, 20.0, 100, "12%",
                        "Default Supplier", LocalDate.now().plusMonths(4), true),
                new Product(null, "Kurkure Masala Munch 50g", "D055", "Snacks", "Chips", 20.0, 20.0, 100, "12%",
                        "Default Supplier", LocalDate.now().plusMonths(4), true),
                new Product(null, "Haldiram Bhujia 200g", "D056", "Snacks", "Namkeen", 55.0, 50.0, 50, "12%",
                        "Default Supplier", LocalDate.now().plusMonths(6), true),
                new Product(null, "Haldiram Aloo Bhujia 150g", "D057", "Snacks", "Namkeen", 40.0, 35.0, 50, "12%",
                        "Default Supplier", LocalDate.now().plusMonths(6), true),
                new Product(null, "Bikaji Bikaneri Bhujia 1kg", "D058", "Snacks", "Namkeen", 240.0, 220.0, 20, "12%",
                        "Default Supplier", LocalDate.now().plusMonths(6), true),
                new Product(null, "Cadbury Dairy Milk 50g", "D059", "Snacks", "Chocolate", 45.0, 45.0, 100, "18%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Cadbury 5 Star 20g", "D060", "Snacks", "Chocolate", 10.0, 10.0, 100, "18%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Nestle KitKat 30g", "D061", "Snacks", "Chocolate", 25.0, 25.0, 100, "18%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Amul Dark Chocolate 150g", "D062", "Snacks", "Chocolate", 110.0, 105.0, 30, "18%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Kellogg's Corn Flakes 500g", "D063", "Breakfast", "Cereal", 195.0, 175.0, 30, "12%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Quaker Oats 1kg", "D064", "Breakfast", "Oats", 185.0, 165.0, 30, "5%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "MTR Rava Idli Mix 500g", "D065", "Breakfast", "Instant Mix", 125.0, 110.0, 30, "5%",
                        "Default Supplier", LocalDate.now().plusMonths(9), true),
                new Product(null, "Yippee Noodles 70g", "D066", "Snacks", "Noodles", 12.0, 12.0, 100, "12%",
                        "Default Supplier", LocalDate.now().plusMonths(9), true),
                new Product(null, "Ching's Secret Hakka Noodles 150g", "D067", "Snacks", "Noodles", 40.0, 35.0, 50,
                        "12%", "Default Supplier", LocalDate.now().plusMonths(9), true),

                // --- PERSONAL CARE (D111 - D160) ---
                new Product(null, "Dettol Soap 125g", "D010", "Personal Care", "Soap", 45.0, 42.0, 100, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Lifebuoy Total 125g", "D068", "Personal Care", "Soap", 35.0, 32.0, 100, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Dove Cream Bar 100g", "D069", "Personal Care", "Soap", 65.0, 60.0, 50, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Lux International 125g", "D070", "Personal Care", "Soap", 40.0, 38.0, 100, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Pears Pure & Gentle 125g", "D071", "Personal Care", "Soap", 55.0, 52.0, 50, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Sunsilk Shampoo 180ml", "D072", "Personal Care", "Shampoo", 135.0, 120.0, 50, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Head & Shoulders 180ml", "D073", "Personal Care", "Shampoo", 165.0, 155.0, 50, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Clinic Plus 180ml", "D074", "Personal Care", "Shampoo", 110.0, 99.0, 50, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Colgate MaxFresh 150g", "D075", "Personal Care", "Toothpaste", 105.0, 95.0, 100,
                        "18%", "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Pepsodent G 150g", "D076", "Personal Care", "Toothpaste", 95.0, 85.0, 100, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Parachute Coconut Oil 200ml", "D077", "Personal Care", "Hair Oil", 90.0, 85.0, 50,
                        "5%", "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Bajaj Almond Drops 100ml", "D078", "Personal Care", "Hair Oil", 65.0, 60.0, 50,
                        "18%", "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Stayfree Secure Pads 8pc", "D079", "Personal Care", "Hygiene", 45.0, 42.0, 50, "0%",
                        "Default Supplier", LocalDate.now().plusYears(3), true),
                new Product(null, "Whisper Choice 8pc", "D080", "Personal Care", "Hygiene", 50.0, 48.0, 50, "0%",
                        "Default Supplier", LocalDate.now().plusYears(3), true),
                new Product(null, "Fair & Lovely 50g", "D081", "Personal Care", "Cream", 110.0, 99.0, 30, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Pond's Talcum Powder 100g", "D082", "Personal Care", "Powder", 85.0, 78.0, 30, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Nivea Soft Cream 100ml", "D083", "Personal Care", "Cream", 165.0, 150.0, 20, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Himalaya Face Wash 100ml", "D084", "Personal Care", "Face Wash", 150.0, 135.0, 30,
                        "18%", "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Gillette Foam 200g", "D085", "Personal Care", "Shaving", 210.0, 195.0, 20, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Park Avenue Deo 150ml", "D086", "Personal Care", "Deodorant", 199.0, 175.0, 20,
                        "18%", "Default Supplier", LocalDate.now().plusYears(3), true),

                // --- HOUSEHOLD (D161 - D200) ---
                new Product(null, "Surf Excel Matic 1kg", "D087", "Household", "Detergent", 230.0, 215.0, 50, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Ariel Top Load 1kg", "D088", "Household", "Detergent", 250.0, 235.0, 50, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Tide Plus 1kg", "D089", "Household", "Detergent", 120.0, 110.0, 100, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Vim Bar 300g", "D090", "Household", "Dishwash", 30.0, 28.0, 200, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Exo Dishwash Round 500g", "D091", "Household", "Dishwash", 55.0, 50.0, 100, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Pril Liquid 500ml", "D092", "Household", "Dishwash", 105.0, 95.0, 50, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Harpic Blue 500ml", "D093", "Household", "Cleaner", 95.0, 89.0, 50, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Lizol Floor Cleaner 500ml", "D094", "Household", "Cleaner", 110.0, 99.0, 50, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Colin Glass Cleaner 500ml", "D095", "Household", "Cleaner", 95.0, 85.0, 30, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Comfort Fabric Conditioner 200ml", "D096", "Household", "Conditioner", 60.0, 55.0,
                        50, "18%", "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Good Knight Liquid Refill", "D097", "Household", "Repellent", 85.0, 78.0, 50, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "All Out Ultra Refill", "D098", "Household", "Repellent", 80.0, 75.0, 50, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Mortein Spray 250ml", "D099", "Household", "Repellent", 165.0, 150.0, 20, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Godrej Aer Spray 220ml", "D100", "Household", "Freshener", 150.0, 135.0, 20, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),

                // --- BEVERAGES & DAIRY (D201 - D250) ---
                new Product(null, "Frooti 1L", "D101", "Beverages", "Juice", 65.0, 60.0, 50, "12%", "Default Supplier",
                        LocalDate.now().plusMonths(6), true),
                new Product(null, "Maaza 1.2L", "D102", "Beverages", "Juice", 75.0, 70.0, 50, "12%", "Default Supplier",
                        LocalDate.now().plusMonths(6), true),
                new Product(null, "Coca Cola 2L", "D103", "Beverages", "Soft Drink", 95.0, 90.0, 50, "28%",
                        "Default Supplier", LocalDate.now().plusMonths(6), true),
                new Product(null, "Pepsi 2L", "D104", "Beverages", "Soft Drink", 95.0, 90.0, 50, "28%",
                        "Default Supplier", LocalDate.now().plusMonths(6), true),
                new Product(null, "Thums Up 2L", "D105", "Beverages", "Soft Drink", 95.0, 90.0, 50, "28%",
                        "Default Supplier", LocalDate.now().plusMonths(6), true),
                new Product(null, "Kinley Water 1L", "D106", "Beverages", "Water", 20.0, 18.0, 200, "18%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Real Orange Juice 1L", "D107", "Beverages", "Juice", 110.0, 99.0, 30, "12%",
                        "Default Supplier", LocalDate.now().plusMonths(6), true),
                new Product(null, "Tropicana Apple Juice 1L", "D108", "Beverages", "Juice", 120.0, 110.0, 30, "12%",
                        "Default Supplier", LocalDate.now().plusMonths(6), true),
                new Product(null, "Red Bull 250ml", "D109", "Beverages", "Energy Drink", 115.0, 110.0, 24, "28%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Glucon-D 500g", "D110", "Beverages", "Energy Drink", 185.0, 175.0, 30, "12%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Amul Butter 100g", "D111", "Dairy", "Butter", 56.0, 54.0, 50, "12%",
                        "Default Supplier", LocalDate.now().plusMonths(6), true),
                new Product(null, "Amul Cheese Slices 200g", "D112", "Dairy", "Cheese", 145.0, 138.0, 30, "12%",
                        "Default Supplier", LocalDate.now().plusMonths(6), true),
                new Product(null, "Hershey's Syrup 623g", "D113", "Dairy", "Syrup", 215.0, 195.0, 20, "12%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Amul Mithai Mate 200g", "D114", "Dairy", "Condensed Milk", 62.0, 60.0, 30, "12%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),

                // --- STAPLES & OTHERS (D251 - D300) ---
                new Product(null, "Besan 500g", "D115", "Staples", "Flour", 65.0, 60.0, 50, "0%", "Default Supplier",
                        LocalDate.now().plusMonths(6), true),
                new Product(null, "Kabuli Chana 500g", "D116", "Pulses", "Dal", 80.0, 75.0, 50, "0%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Peanut 500g", "D117", "Staples", "Nuts", 95.0, 85.0, 50, "0%", "Default Supplier",
                        LocalDate.now().plusYears(1), true),
                new Product(null, "Walnut 250g", "D118", "Staples", "Dry Fruit", 350.0, 320.0, 20, "12%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Almonds 250g", "D119", "Staples", "Dry Fruit", 240.0, 220.0, 30, "12%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Cashew 250g", "D120", "Staples", "Dry Fruit", 260.0, 240.0, 30, "12%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Gowardhan Ghee 1L", "D121", "Dairy", "Ghee", 650.0, 620.0, 20, "12%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Everest Sabji Masala 100g", "D122", "Spices", "Masala", 65.0, 60.0, 50, "5%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "MDH Deggi Mirch 100g", "D123", "Spices", "Spice", 85.0, 78.0, 50, "5%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Catch Mustard Seeds 100g", "D124", "Spices", "Spice", 25.0, 22.0, 100, "5%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Tata Tea Gold 500g", "D125", "Beverages", "Tea", 345.0, 320.0, 30, "5%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Saffola Active Heat 1L", "D126", "Oils", "Oils", 160.0, 145.0, 30, "5%",
                        "Default Supplier", LocalDate.now().plusMonths(9), true),
                new Product(null, "Bajaj Almond Oil 100ml", "D127", "Personal Care", "Hair Oil", 120.0, 110.0, 30,
                        "18%", "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Patanjali Dant Kanti 100g", "D128", "Personal Care", "Toothpaste", 55.0, 50.0, 100,
                        "18%", "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Dabur Red Paste 100g", "D129", "Personal Care", "Toothpaste", 65.0, 60.0, 50, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Zandu Balm 10g", "D130", "Health", "Medicine", 45.0, 42.0, 50, "12%",
                        "Default Supplier", LocalDate.now().plusYears(3), true),
                new Product(null, "Vicks Vaporub 25g", "D131", "Health", "Medicine", 95.0, 88.0, 50, "12%",
                        "Default Supplier", LocalDate.now().plusYears(3), true),
                new Product(null, "Vaseline Jelly 50g", "D132", "Personal Care", "Cream", 75.0, 70.0, 50, "18%",
                        "Default Supplier", LocalDate.now().plusYears(3), true),
                new Product(null, "Boroplus Cream 40ml", "D133", "Personal Care", "Cream", 70.0, 65.0, 50, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Tide Bar 150g", "D134", "Household", "Detergent", 15.0, 15.0, 200, "18%",
                        "Default Supplier", LocalDate.now().plusYears(3), true),
                new Product(null, "Wheel Lemon 1kg", "D135", "Household", "Detergent", 65.0, 60.0, 100, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Rin Bar 250g", "D136", "Household", "Detergent", 25.0, 24.0, 200, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Domex Cleaner 500ml", "D137", "Household", "Cleaner", 90.0, 82.0, 50, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Dettol Liquid 500ml", "D138", "Health", "Antiseptic", 185.0, 175.0, 30, "12%",
                        "Default Supplier", LocalDate.now().plusYears(3), true),
                new Product(null, "Savlon Liquid 500ml", "D139", "Health", "Antiseptic", 160.0, 150.0, 30, "12%",
                        "Default Supplier", LocalDate.now().plusYears(3), true),
                new Product(null, "Hand Sanitizer 100ml", "D140", "Health", "Hygiene", 50.0, 45.0, 100, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Agarbatti Pack", "D141", "Household", "Pooja", 35.0, 30.0, 100, "5%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Cotton Bales 100g", "D142", "Household", "Pooja", 45.0, 40.0, 50, "5%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Matchbox 10pc", "D143", "Household", "Staples", 10.0, 10.0, 200, "5%",
                        "Default Supplier", LocalDate.now().plusYears(3), true),
                new Product(null, "Candle Pack", "D144", "Household", "Staples", 25.0, 25.0, 100, "12%",
                        "Default Supplier", LocalDate.now().plusYears(3), true),
                new Product(null, "Napkins 100pc", "D145", "Household", "Paper", 45.0, 40.0, 50, "12%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Kitchen Roll 1pc", "D146", "Household", "Paper", 65.0, 60.0, 30, "12%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Dustbin Bags 30pc", "D147", "Household", "Plastic", 95.0, 85.0, 50, "18%",
                        "Default Supplier", LocalDate.now().plusYears(3), true),
                new Product(null, "Scrub Pad 1pc", "D148", "Household", "Cleaning", 15.0, 15.0, 200, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Steel Wool 1pc", "D149", "Household", "Cleaning", 20.0, 20.0, 200, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Harpic Red 500ml", "D150", "Household", "Cleaner", 90.0, 82.0, 50, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),

                // --- ADDITIONAL ITEMS (D151 - D200+) ---
                new Product(null, "Maggi Magic Masala 6g", "D151", "Spices", "Masala", 5.0, 5.0, 500, "5%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Everest Kasuri Methi 25g", "D152", "Spices", "Spice", 25.0, 22.0, 100, "5%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Catch Black Salt 100g", "D153", "Spices", "Salt", 20.0, 18.0, 100, "5%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "MDH Amchur Powder 100g", "D154", "Spices", "Powder", 65.0, 60.0, 50, "5%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Everest Chat Masala 100g", "D155", "Spices", "Masala", 65.0, 60.0, 50, "5%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Patanjali Cow Ghee 500ml", "D156", "Dairy", "Ghee", 310.0, 295.0, 30, "12%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Nestle Everyday Milk Powder 200g", "D157", "Dairy", "Milk Powder", 110.0, 105.0, 50,
                        "12%", "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Amul Taaza Milk 1L", "D158", "Dairy", "Milk", 66.0, 66.0, 100, "0%",
                        "Default Supplier", LocalDate.now().plusDays(90), true),
                new Product(null, "Mother Dairy Ghee 500ml", "D159", "Dairy", "Ghee", 315.0, 300.0, 20, "12%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Bansi Sooji 500g", "D160", "Staples", "Sooji", 40.0, 35.0, 50, "0%",
                        "Default Supplier", LocalDate.now().plusMonths(6), true),
                new Product(null, "Bansi Rawa 500g", "D161", "Staples", "Rawa", 40.0, 35.0, 50, "0%",
                        "Default Supplier", LocalDate.now().plusMonths(6), true),
                new Product(null, "Patanjali Poha 500g", "D162", "Staples", "Poha", 50.0, 45.0, 50, "0%",
                        "Default Supplier", LocalDate.now().plusMonths(6), true),
                new Product(null, "Gowardhan Paneer 200g", "D163", "Dairy", "Paneer", 95.0, 90.0, 30, "0%",
                        "Default Supplier", LocalDate.now().plusDays(30), true),
                new Product(null, "Amul Paneer 200g", "D164", "Dairy", "Paneer", 100.0, 95.0, 30, "0%",
                        "Default Supplier", LocalDate.now().plusDays(30), true),
                new Product(null, "Mother Dairy Paneer 200g", "D165", "Dairy", "Paneer", 98.0, 92.0, 30, "0%",
                        "Default Supplier", LocalDate.now().plusDays(30), true),
                new Product(null, "Dabur Gulabari 100ml", "D166", "Personal Care", "Skincare", 55.0, 50.0, 50, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Himalaya Neem Face Wash 50ml", "D167", "Personal Care", "Face Wash", 75.0, 70.0, 50,
                        "18%", "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Dettol Handwash Refill 175ml", "D168", "Personal Care", "Handwash", 45.0, 40.0, 100,
                        "18%", "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Lifebuoy Handwash Refill 175ml", "D169", "Personal Care", "Handwash", 40.0, 38.0,
                        100, "18%", "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Savlon Handwash Refill 175ml", "D170", "Personal Care", "Handwash", 35.0, 32.0, 100,
                        "18%", "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Santur Soap 125g", "D171", "Personal Care", "Soap", 35.0, 32.0, 100, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Cinthol Soap 125g", "D172", "Personal Care", "Soap", 40.0, 38.0, 100, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Hamam Soap 125g", "D173", "Personal Care", "Soap", 38.0, 35.0, 100, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Margo Soap 125g", "D174", "Personal Care", "Soap", 35.0, 32.0, 100, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Medimix Soap 125g", "D175", "Personal Care", "Soap", 42.0, 38.0, 50, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Colgate Strong Teeth 100g", "D176", "Personal Care", "Toothpaste", 55.0, 50.0, 100,
                        "18%", "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Close-Up Red Hot 100g", "D177", "Personal Care", "Toothpaste", 60.0, 55.0, 50, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Sensodyne Fresh 100g", "D178", "Personal Care", "Toothpaste", 120.0, 110.0, 30,
                        "18%", "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Oral-B Toothbrush 1pc", "D179", "Personal Care", "Toothbrush", 35.0, 30.0, 100,
                        "18%", "Default Supplier", LocalDate.now().plusYears(3), true),
                new Product(null, "Colgate ZigZag 1pc", "D180", "Personal Care", "Toothbrush", 30.0, 25.0, 100, "18%",
                        "Default Supplier", LocalDate.now().plusYears(3), true),
                new Product(null, "Clinic Plus Sachet 1pc", "D181", "Personal Care", "Shampoo", 1.0, 1.0, 1000, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Sunsilk Sachet 1pc", "D182", "Personal Care", "Shampoo", 1.0, 1.0, 1000, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Dove Sachet 1pc", "D183", "Personal Care", "Shampoo", 2.0, 2.0, 500, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Pantene Sachet 1pc", "D184", "Personal Care", "Shampoo", 2.0, 2.0, 500, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Vatika Hair Oil 100ml", "D185", "Personal Care", "Hair Oil", 65.0, 60.0, 50, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Keo Karpin 100ml", "D186", "Personal Care", "Hair Oil", 60.0, 55.0, 50, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Nihar Shanti Amla 100ml", "D187", "Personal Care", "Hair Oil", 45.0, 40.0, 100,
                        "18%", "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Rin Detergent Powder 1kg", "D188", "Household", "Detergent", 95.0, 85.0, 100, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Ghadi Detergent 1kg", "D189", "Household", "Detergent", 65.0, 60.0, 200, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Active Wheel 1kg", "D190", "Household", "Detergent", 70.0, 65.0, 100, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Vim Liquid 500ml", "D191", "Household", "Dishwash", 110.0, 99.0, 50, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Gala Floor Cloth 1pc", "D192", "Household", "Cleaning", 45.0, 40.0, 100, "12%",
                        "Default Supplier", LocalDate.now().plusYears(3), true),
                new Product(null, "Scrub Sponge 1pc", "D193", "Household", "Cleaning", 25.0, 20.0, 100, "12%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Margo Neem Soap 125g", "D194", "Personal Care", "Soap", 40.0, 38.0, 50, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Godrej No.1 Soap 125g", "D195", "Personal Care", "Soap", 30.0, 28.0, 100, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Dettol Liquid Refill 750ml", "D196", "Personal Care", "Handwash", 105.0, 95.0, 30,
                        "18%", "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Harpic Lysol Combo", "D197", "Household", "Cleaning", 190.0, 175.0, 20, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Good Knight Gold Refill", "D198", "Household", "Repellent", 95.0, 85.0, 50, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Hit Spray 250ml", "D199", "Household", "Repellent", 185.0, 170.0, 20, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Comfort Lavender 200ml", "D200", "Household", "Conditioner", 65.0, 60.0, 50, "18%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Eveready Battery AA 4pc", "D201", "Household", "Battery", 60.0, 55.0, 50, "18%",
                        "Default Supplier", LocalDate.now().plusYears(3), true),
                new Product(null, "Duracell AA 2pc", "D202", "Household", "Battery", 140.0, 130.0, 30, "18%",
                        "Default Supplier", LocalDate.now().plusYears(5), true),
                new Product(null, "Phillips LED Bulb 9W", "D203", "Household", "Lighting", 110.0, 95.0, 20, "12%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Syska LED Bulb 9W", "D204", "Household", "Lighting", 100.0, 85.0, 20, "12%",
                        "Default Supplier", LocalDate.now().plusYears(2), true),
                new Product(null, "Broom Grass 1pc", "D205", "Household", "Cleaning", 120.0, 110.0, 30, "12%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Floor Wiper 1pc", "D206", "Household", "Cleaning", 150.0, 140.0, 20, "12%",
                        "Default Supplier", LocalDate.now().plusYears(1), true),
                new Product(null, "Plastic Bucket 15L", "D207", "Household", "Plastic", 180.0, 160.0, 10, "18%",
                        "Default Supplier", LocalDate.now().plusYears(5), true),
                new Product(null, "Plastic Mug 1L", "D208", "Household", "Plastic", 35.0, 30.0, 20, "18%",
                        "Default Supplier", LocalDate.now().plusYears(5), true),
                new Product(null, "Dustpan 1pc", "D209", "Household", "Plastic", 45.0, 40.0, 20, "18%",
                        "Default Supplier", LocalDate.now().plusYears(5), true),
                new Product(null, "Nylon Rope 10m", "D210", "Household", "Hardware", 55.0, 50.0, 30, "18%",
                        "Default Supplier", LocalDate.now().plusYears(5), true));

        productRepository.saveAll(defaultProducts);
        System.out.println("Seeded " + defaultProducts.size() + " default products for Indian grocery shops.");
    }
}
