spring.datasource.url=jdbc:h2:file:~/smms_data/smms_db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;CACHE_SIZE=32768;LOCK_TIMEOUT=10000;MV_STORE=TRUE;OPTIMIZE_REUSE_RESULTS=TRUE

spring.jpa.open-in-view=false

smms.payment.offline-mode=false
smms.mail.offline-mode=true

razorpay.key.id=rzp_live_Rz8vO7gI0lkWTk
razorpay.key.secret=eoF7UrrVeVZD3JTSzd9k5KD5

spring.mail.host=localhost
spring.mail.port=2525
spring.mail.username=tsaritservices@gmail.com
spring.mail.password=hvun iqcx yhwd mrlj
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false
